### ISSUE TITLE
Reservations

### ISSUE THREAD

**Issue by petermikitsh** [ritstudentgovernment/BikeShare#54]
It may be valuable to users if they could schedule reservations. Given the system's high demand, it's often challenging to get a bike. Are there any stats on how many students walk into Gleason Office but get turned away due to no bikes being around? Or perhaps this could be determined from analyzing web traffic (bounce rate for the racks page). Those numbers may give us insight into how useful the feature would be.

**Comment by NathanCastle** [comment]
I discussed it with the folks at Parking & Transportation Services and they weren't in agreement that this should be implemented. The concern wasn't about the idea, which they liked, but that adding the concept would make the system more complicated to administer.
